name: Build

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:
    
env:
  BUILD_TYPE: Release

jobs:

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      if: github.event_name == 'workflow_dispatch'
    - name: Create tag
      id: create_tag
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          tag=v$(date +%Y%m%d.%H%M%S)
        else
          tag=$(basename "${{ github.ref }}")
        fi
        echo "tag=$tag" >> $GITHUB_OUTPUT
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.tag }}
        draft: true
        prerelease: false

  build_web:
  
    name: Build (Web)
    needs: [release]
    runs-on: ubuntu-latest
  
    steps:
        
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y libpulse-dev libgl1-mesa-dev
  
    - name: Cache LLVM host
      id: cache-llvm-host
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/build_llvm
        key: web-cache-llvm-host
  
    - name: Build LLVM host
      if: steps.cache-llvm-host.outputs.cache-hit != 'true'
      run: |
        cmake -B ${{github.workspace}}/build_llvm -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLLVM_TARGETS_TO_BUILD=WebAssembly -DLLVM_ENABLE_PROJECTS="clang" -S ${{github.workspace}}/deps/llvm-project/llvm
        cmake --build ${{github.workspace}}/build_llvm --config ${{env.BUILD_TYPE}} -- llvm-tblgen
        cmake --build ${{github.workspace}}/build_llvm --config ${{env.BUILD_TYPE}} -- clang-tblgen
      
    - name: Set up emsdk
      run: |
        git clone https://github.com/emscripten-core/emsdk.git ${{github.workspace}}/emsdk
        ${{github.workspace}}/emsdk/emsdk install 3.1.31
        ${{github.workspace}}/emsdk/emsdk activate 3.1.31
  
    - name: Configure
      run: |
        source ${{github.workspace}}/emsdk/emsdk_env.sh
        emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLLVM_TABLEGEN=${{github.workspace}}/build_llvm/bin/llvm-tblgen -DCLANG_TABLEGEN=${{github.workspace}}/build_llvm/bin/clang-tblgen
    
    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        mkdir ${{github.workspace}}/arduboy_sim_web
        
    - name: Create zip file
      run: |
        cp ${{github.workspace}}/build/arduboy_sim.js ${{github.workspace}}/arduboy_sim_web
        cp ${{github.workspace}}/build/arduboy_sim.wasm ${{github.workspace}}/arduboy_sim_web
        cp ${{github.workspace}}/build/arduboy_sim_player.js ${{github.workspace}}/arduboy_sim_web
        cp ${{github.workspace}}/build/arduboy_sim_player.wasm ${{github.workspace}}/arduboy_sim_web
        cp ${{github.workspace}}/src/arduboy_sim.html ${{github.workspace}}/arduboy_sim_web/index.html
        cp ${{github.workspace}}/src/arduboy_sim_player.html ${{github.workspace}}/arduboy_sim_web/player.html
        cd ${{github.workspace}}/arduboy_sim_web
        zip -r ${{github.workspace}}/arduboy_sim_web.zip *
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: ${{github.workspace}}/arduboy_sim_web
  
    - name: Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/arduboy_sim_web.zip
        asset_name: arduboy_sim_web.zip
        asset_content_type: application/zip

  #build_ubuntu:
  #
  #  runs-on: ubuntu-latest
  #
  #  steps:
  #  - name: Checkout
  #    uses: actions/checkout@v3
  #    with:
  #      submodules: 'recursive'
  #      
  #  - name: Install prerequisites
  #    run: sudo apt-get install -y libpulse-dev libgl1-mesa-dev
  #
  #  - name: Configure
  #    run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  #
  #  - name: Build
  #    run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  #
  #  - name: Upload Build Artifact
  #    uses: actions/upload-artifact@v3.1.2
  #    with:
  #      name: Release_Ubuntu
  #      path: ${{github.workspace}}/build/arduboy_sim

  build_windows_x86:
  
    name: Build (Windows x86)
    needs: [release]
    runs-on: windows-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
  
    - name: Configure
      run: cmake -B ${{github.workspace}}/build -A Win32 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target arduboy_sim
  
    - name: Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/arduboy_sim.exe
        asset_name: arduboy_sim_x86.exe
        asset_content_type: application/octet-stream
  
  build_windows_x64:
  
    name: Build (Windows x64)
    needs: [release]
    runs-on: windows-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
  
    - name: Configure
      run: cmake -B ${{github.workspace}}/build -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target arduboy_sim
  
    - name: Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/arduboy_sim.exe
        asset_name: arduboy_sim_x64.exe
        asset_content_type: application/octet-stream
  
  #build_macos:
  #
  #  runs-on: macos-latest
  #
  #  steps:
  #  - name: Checkout
  #    uses: actions/checkout@v3
  #    with:
  #      submodules: 'recursive'
  #
  #  - name: Configure
  #    run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  #
  #  - name: Build
  #    run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  #
  #  - name: Upload Build Artifact
  #    uses: actions/upload-artifact@v3.1.2
  #    with:
  #      name: Release_MacOS
  #      path: ${{github.workspace}}/build/arduboy_sim
